### ISSUE TITLE
Getting "relation "icustay_detail" does not exist" when running "make build_curated_from_psql"

### ISSUE THREAD

**Issue by manisci** [MLforHealth/MIMIC_Extract#18]
Hi,

Thanks, for your detailed documentation. I've tried to follow the instructions as closely as possible, I've done "make concepts" from the original mimic repository and also successfully done "make build_concepts " from this repository. Looking at concepts in the directory of mimic data folder, I have this:

![image](https://user-images.githubusercontent.com/30268711/71594977-e7168680-2b07-11ea-9a49-bae30f16584e.png)

Also in curated folder of mimic extract folder, I only have "static_data.csv". 
This is a snapshot of the error I'm getting.
![image](https://user-images.githubusercontent.com/30268711/71595147-82a7f700-2b08-11ea-988d-17476c0bf45d.png)

Do you have any idea what might be the issue?

Thanks :)

**Comment by singhalrk** [comment]
You have to run build concepts before you run build_curated_from_psql.

**Comment by mmcdermott** [comment]
Apologies for the slow response. @singhalrk is correct; however, MIMIC also modified their code-base in the interim rendering our README instructions insufficient to build concepts. We've just pushed a new release, with new instructions, which we believe should have fixed this and all outstanding issues. Please re-open if you encounter any new issues.

**Comment by zhangyongheng78** [comment]
Hi @mmcdermott, I still have the same error. 
I followed the https://github.com/MIT-LCP/mimic-code and as a result, icustay_detail is in the public schema instead of the mimiciii schema. Is this the reason why I encounter the same error?

I tried to change         https://github.com/MLforHealth/MIMIC_Extract/blob/420bfc4122cd267ae92c2934fb4f49dcc2aed577/mimic_querier.py#L28 to schema_name='public' but still does not work

**Comment by zhangyongheng78** [comment]
> Hi @mmcdermott, I still have the same error.
> I followed the https://github.com/MIT-LCP/mimic-code and as a result, icustay_detail is in the public schema instead of the mimiciii schema. Is this the reason why I encounter the same error?
> 
> I tried to change
> 
> https://github.com/MLforHealth/MIMIC_Extract/blob/420bfc4122cd267ae92c2934fb4f49dcc2aed577/mimic_querier.py#L28
> 
> to schema_name='public' but still does not work

The issue is resolved by calling ```public.icustay_detail```

**Comment by mmcdermott** [comment]
HI @zhangyongheng78 -- thanks for reaching out. It seems like LCP has changed their instructions / code once again, and as of 10 months ago these concepts are indeed built in the public schema, not the mimiciii schema. You are correct that the indicated change is all that should be required. I'll re-open this issue for tracking. Thanks for catching this!

**Comment by fahim-sikder** [comment]
Hi, as the LCP, creates the concepts in the public schema we have to both use the public and mimiciii schema. I changed line 28 on `MIMIC_Extract/mimic_querier.py` by this `schema_name='public,mimiciii'` also changed the line 737 on the `MIMIC_Extract/mimic_direct_extract.py` to `ap.add_argument('--psql_schema_name', type=str, default='public,mimiciii',
                    help='Postgres database name.')`

Now, it is running!

**Comment by mmcdermott** [comment]
Thanks @fahim-sikder! I've not had time to in and incorporate any changes, but that comment is really helpful and will help others who run into the same issue.

**Comment by mz4987** [comment]
> Thanks @fahim-sikder! I've not had time to in and incorporate any changes, but that comment is really helpful and will help others who run into the same issue.

I have modified the file based on previous discussion. However, I still not able to read the public.icustay_detail table. I did find this table in public schema.
<img width="192" alt="image" src="https://user-images.githubusercontent.com/63058110/163309552-e8cb122a-ff76-494a-a486-633c175c4734.png">

I noticed that some tables were dropped when I created the database. Is this correct? I believe I have downloaded all the tables. Not sure if I have missed anything. 
![image](https://user-images.githubusercontent.com/63058110/163310043-a891e81c-530e-439e-9af2-b1469b8273af.png)

Thanks for helping!

**Comment by mit2400** [comment]
@mz4987 
It's because some queries do not use ` --psql_schema_name`.
> such as, "mimiciii.ccs_dx" in SQL_Queries/codes.sql

So, I made a pull request (#66) which simply changes search path of queries.
I hope it fixes your problem!

**Comment by aspargo2** [comment]
It appears this is still an issue. I don't see that table in the mimiciii data, does anyone know where that is supposed to be coming from?

**Comment by c3-aspargo** [comment]
The colloid_bolus.sql file doesn't appear to have "DATETIME" in it anywhere either which causes the sed command to return nothing :/

installing:
```
brew install gnu-sed
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
```
then changing sed to gsed fixed that

**Comment by c3-aspargo** [comment]
> It appears this is still an issue. I don't see that table in the mimiciii data, does anyone know where that is supposed to be coming from?

I needed to run the functions to load the mimic concepts here:
https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iii/concepts
